default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: db/insta_development

test:
  <<: *default
  database: db/insta_test

production:
  <<: *default
  database: insta_production
  username: insta
  password: <%= ENV['INSTA_DATABASE_PASSWORD'] %>
